Port the Dockerfiles to aarch64
Mbed-TLS/mbedtls-test pull request #109
Opened 2023-06-29 17:37 UTC by bensze01

This allows us to build the Dockerfiles on aarch64 hosts, and run 32-bit and 64-bit Arm tests natively.

Supersedes #35.

Ci-runs: 
 - development
   - head
     - [Internal CI][1]
     - [OpenCI][6]
   - merge
     - [Internal CI][2]
     - [OpenCI][7]
   - deliberate ABI-break
     - [Internal CI][3]
     - [OpenCI][8]
 - 2.28
   - head
     - [Internal CI][4]
     - [OpenCI][9]
   - merge
     - [Internal CI][5]
     - [Open CI][10]
   
[1]:  https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-ci-testing/view/change-requests/job/PR-906-head/66/
[2]:  https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-ci-testing/view/change-requests/job/PR-906-merge/120/
[3]:  https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-ci-testing/view/change-requests/job/PR-758-merge/12/
[4]:  https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-ci-testing/view/change-requests/job/PR-850-head/5/
[5]:  https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-ci-testing/view/change-requests/job/PR-850-merge/10/
[6]:  https://ci.trustedfirmware.org/view/Mbed-TLS/job/mbed-tls-restricted-pr-ci-testing/view/change-requests/job/PR-906-head/2/
[7]:  https://ci.trustedfirmware.org/view/Mbed-TLS/job/mbed-tls-restricted-pr-ci-testing/view/change-requests/job/PR-906-merge/2/
[8]:  https://ci.trustedfirmware.org/view/Mbed-TLS/job/mbed-tls-restricted-pr-ci-testing/view/change-requests/job/PR-758-merge/2/
[9]:  https://ci.trustedfirmware.org/view/Mbed-TLS/job/mbed-tls-restricted-pr-ci-testing/view/change-requests/job/PR-850-head/2/
[10]: https://ci.trustedfirmware.org/view/Mbed-TLS/job/mbed-tls-restricted-pr-ci-testing/view/change-requests/job/PR-850-merge/2/

2023-07-03 07:20 UTC, yuhaoth submitted a review, later dismissed
LGTM

2023-07-03 07:35 UTC, tom-cosgrove-arm commented on resources/docker_files/ubuntu-16.04/Dockerfile
>  # Support for i386, for 32-bit builds+tests of Mbed TLS
Stale comment, should now be something along the lines of

```
# Add support for 32-bit builds+tests of Mbed TLS where we can
```

2023-07-03 07:37 UTC, tom-cosgrove-arm commented on resources/docker_files/ubuntu-18.04/Dockerfile
>  # Support for i386, for 32-bit builds+tests of Mbed TLS
Similarly stale comment

2023-07-03 07:38 UTC, tom-cosgrove-arm commented on resources/docker_files/ubuntu-16.04/Dockerfile
>  # Install all the parts of gcc-multilib, which is necessary for 32-bit builds.
I presume `gcc-multilib` is x86_64-specific?

2023-07-03 07:39 UTC, tom-cosgrove-arm commented on resources/docker_files/ubuntu-20.04/Dockerfile
>  # Support for i386, for 32-bit builds+tests of Mbed TLS
Stale comment

2023-07-03 17:25 UTC, gilles-peskine-arm requested changes
LGTM apart from a couple of comments that need updating.

Please link to test runs on both CIs.

2023-07-03 17:25 UTC, gilles-peskine-arm commented on resources/docker_files/ubuntu-16.04/Dockerfile
>  # Install all the parts of gcc-multilib, which is necessary for 32-bit builds.
It's not, but it's missing on some architectures (depending on the Ubuntu release, see https://packages.ubuntu.com/search?keywords=gcc-multilib).

2023-07-03 17:25 UTC, gilles-peskine-arm commented on resources/docker_files/ubuntu-16.04/Dockerfile
> +# Install arm-linux-gnueabi-gcc and arm-none-eabi-gcc - to cross-build Mbed TLS
I think the comment about a lack of an armel port belongs here. Otherwise, why would we install `gcc-arm-linux-gnueabi` if already running on arm?

2023-07-07 15:35 UTC, bensze01 commented on resources/docker_files/ubuntu-16.04/Dockerfile
> +# Install arm-linux-gnueabi-gcc and arm-none-eabi-gcc - to cross-build Mbed TLS
We would have to install `gcc-arm-linux-gnueabi` even if there was an `armel` port - it allows us to compile the Thumb-1 tests. We don't really care about the host architecture of the compiler, only the target architecture.

2023-07-10 12:32 UTC, bensze01 commented
I've updated the description with the CI runs. The OpenCI ones (except the deliberate ABI break) are still running at the time of writing.

2023-07-10 15:03 UTC, gilles-peskine-arm approved these changes
LGTM if the CI results are satisfactory.

2023-07-11 06:42 UTC, bensze01 commented
All the CI runs completed successfully.

2023-07-12 13:13 UTC, tom-cosgrove-arm approved these changes
LGTM

2023-07-12 13:16 UTC, merged