Add earliest and latest compilers
Mbed-TLS/mbedtls-test pull request #118
Opened 2023-07-20 22:46 UTC by gowthamsk-arm

This commit updates the Ubuntu 16.04 docker file to include the earliest versions of GCC (4.7) and Clang (3.5) available in 16.04. For Ubuntu 22.04 the latest compiler versions of GCC (12) and Clang (16) are installed.

Also creates couple of symlinks of those compilers for simplified usage in the all.sh script.

Resolves #110

2023-07-21 10:27 UTC, gilles-peskine-arm commented
Test jobs on OpenCI:

* [development](https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/2/)
* [mbedtls-2.28](https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/3/)
* [use_earliest_latest_compilers](https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/4/)
* [use_earliest_latest_compilers_2.28](https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/5/)

2023-07-25 18:41 UTC, gilles-peskine-arm requested changes
A few minor change requests.

The test results look good, but we'll have to re-run at least some after updating the docker files.

2023-07-25 18:41 UTC, gilles-peskine-arm commented on resources/docker_files/ubuntu-16.04/Dockerfile
> +    ln -s /usr/bin/gcc-4.7 /usr/bin/gcc-earliest && \
Please create the symlinks in `/usr/local/bin`. `/usr` is for what comes with the distribution. Also applies in the 22.04 dockerfile.

2023-07-25 18:41 UTC, gilles-peskine-arm commented on resources/docker_files/ubuntu-22.04/Dockerfile
> +    software-properties-common && \
Please group all the installations from the standard repository in the same batch. It makes the file easier to read and the caching of intermediate steps more efficient.

2023-07-25 18:41 UTC, gilles-peskine-arm commented on resources/docker_files/ubuntu-22.04/Dockerfile
> +    # to build Mbed TLS using latest gcc version
More precisely, latest gcc version available from Ubuntu.

2023-07-25 18:41 UTC, gilles-peskine-arm commented on resources/docker_files/ubuntu-22.04/Dockerfile
> +    # to build Mbed TLS using latest clang version
More precisely, the latest clang version at the time of writing. (As opposed to: at the time the docker image is built, or at the time the tests run.)

2023-07-27 07:22 UTC, gowthamsk-arm commented
Test jobs on OpenCI:

[development](https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/20/) → PASS
[mbedtls-2.28](https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/24/) → PASS
[use_earliest_latest_compilers](https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/22/) → PASS
[use_earliest_latest_compilers_2.28](https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/26/) → PASS

Test jobs on internal CI:

[use_earliest_latest_compilers](https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/519/) → PASS
[use_earliest_latest_compilers-2.28](https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/520/) → PASS

2023-07-27 13:07 UTC, tgonzalezorlandoarm approved these changes
LGTM

2023-07-27 13:16 UTC, gilles-peskine-arm requested changes
Just a few readability issues

2023-07-27 13:17 UTC, gilles-peskine-arm commented
Note: in the future, please address review comments in new commits, rather than by pushing a new history, unless there's a good reason to overwrite the existing history.

2023-07-27 13:25 UTC, gowthamsk-arm commented on resources/docker_files/ubuntu-22.04/Dockerfile
> +        gcc-12 \
Will fix it.

2023-07-27 13:25 UTC, gowthamsk-arm commented on resources/docker_files/ubuntu-22.04/Dockerfile
> +        &&  add-apt-repository 'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-16 main' -y \
Will change it.

2023-07-27 13:42 UTC, gilles-peskine-arm approved these changes
Looks good to me on code review. I'll check the CI logs when it's run on the latest release (no need to re-run all jobs, but at least build the image on both jenkins instances).

2023-07-27 13:46 UTC, gowthamsk-arm commented
Thanks for the review :) 
I will trigger a job on both internal and external CIs.

2023-07-27 13:51 UTC, gowthamsk-arm commented
Triggered. 
Internal CI run: https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/521/
External Ci run: https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/27/

2023-07-28 08:09 UTC, gowthamsk-arm commented
Both internal and external CI runs are green :)

2023-07-28 10:29 UTC, merged