Add test job for crypto repo
Mbed-TLS/mbedtls-test pull request #123
Opened 2023-09-20 17:10 UTC by bensze01

Changes and fixes needed to add test jobs for the crypto repo

2023-09-21 13:23 UTC, ronald-cron-arm requested changes
This looks sensible to me. A few suggestions and one question.

2023-09-21 13:23 UTC, ronald-cron-arm commented on vars/psa_crypto.groovy
> +    mbedtls.run_pr_job(true, 'crypto')
```suggestion
    mbedtls.run_pr_job(true, 'psa-crypto')
```
actual name of the repo?

2023-09-22 14:07 UTC, bensze01 commented on vars/environ.groovy
> +    if (!(env.BRANCH_NAME ==~ /PR-\d+-merge/)) {
`BRANCH_NAME` is [set automatically in multibranch pipelines][1] by the branch source, in our case the [Github Branch Source plugin][2]

[1]: https://www.jenkins.io/doc/book/pipeline/multibranch/#additional-environment-variables
[2]: https://plugins.jenkins.io/github-branch-source/

2023-09-25 10:06 UTC, ronald-cron-arm requested changes
Just one question, otherwise this looks good to me.

2023-09-25 10:06 UTC, ronald-cron-arm commented on vars/psa_crypto.groovy
> +        throw new FlowInterruptedException(Result.NOT_BUILT, new CauseOfInterruption[0])
Hopefully this will not result in PRs targeting the development branch having a failed check and thus not a green "Merge pull request" button, right?

2023-09-25 11:36 UTC, bensze01 commented on vars/psa_crypto.groovy
> +        throw new FlowInterruptedException(Result.NOT_BUILT, new CauseOfInterruption[0])
No, it won't. We error out before any statuses are sent to Github. I've also disabled all of the automatic status reports that are not sent by our own groovy code, so those won't show up either.

2023-09-25 11:40 UTC, ronald-cron-arm submitted a review, later dismissed
LGTM, thanks.

2023-09-25 13:09 UTC, davidhorstmann-arm approved these changes
LGTM

2023-09-25 13:14 UTC, gilles-peskine-arm commented on vars/environ.groovy
> +void set_pr_environment(boolean is_production, String repo='tls') {
Can we make `repo` some kind of enum?

2023-09-25 13:15 UTC, davidhorstmann-arm commented on vars/psa_crypto.groovy
> +        echo 'PR target is not "main" branch - not building.'
`main` is the only branch that contains `all.sh`. The other branches are just templates that don't have everything imported from the `mbedtls` repo. Once we move crypto development to this repo, this condition should go away.

2023-09-25 13:15 UTC, davidhorstmann-arm commented on vars/psa_crypto.groovy
> +        echo 'PR target is not "main" branch - not building.'
Ooh jinx

2023-09-25 13:19 UTC, ronald-cron-arm commented on vars/psa_crypto.groovy
> +        echo 'PR target is not "main" branch - not building.'
We do not want to build the 'development' branch (only the build system, doc and tree skeleton) and we have only two maintained branches currently thus this test does the job considering those two branches. Taking into consideration other working branches based on `main`,   ```if (env.TARGET_BRANCH == 'development')``` is probably better.

2023-09-25 13:27 UTC, gilles-peskine-arm commented on vars/psa_crypto.groovy
> +        echo 'PR target is not "main" branch - not building.'
So without this, on branches that aren't up-to-date with `main`, the CI will break, presumably with some weird but debuggable error message. With this, on branches that aren't up-to-date with `main`, the CI will break, with a message that clearly shows where but not why. What benefit does this check have?

2023-09-25 13:35 UTC, ronald-cron-arm commented on vars/psa_crypto.groovy
> +        echo 'PR target is not "main" branch - not building.'
I thought the test was added in the first place to avoid the CI reporting back errors on PRs targeting the development branch. But I did not check it. @bensze01, was that the reason? If that the case I would prefer to keep filtering here the `development` branch, otherwise no test is fine by me.

2023-09-25 13:36 UTC, bensze01 commented on vars/psa_crypto.groovy
> +        echo 'PR target is not "main" branch - not building.'
In the psa-crypto branch we have:
 - PRs that target `development`
    - working on the tooling for extracting psa-crypto from MbedTLS, no MbedTLS files, currently "untestable" without cloning MbedTLS as well
  - PRs that target `main`
    - include all necessary files from MbedTLS, testable without cloning any other repo
    
 This check exists because there is no facility outside groovy to filter branches based on the target branch.
 The check aborts builds for branches where the test logic doesn't exist yet, before any status updates are sent to github.

2023-09-25 13:39 UTC, bensze01 commented on vars/psa_crypto.groovy
> +        echo 'PR target is not "main" branch - not building.'
@ronald-cron-arm Yes, the reason for the check is to prevent jenkins from reporting spurious errors to github.

2023-09-25 13:41 UTC, ronald-cron-arm commented on vars/psa_crypto.groovy
> +        echo 'PR target is not "main" branch - not building.'
> @ronald-cron-arm Yes, the reason for the check is to prevent jenkins from reporting spurious errors to github.

okay, thanks. Then, what about `if (env.TARGET_BRANCH == 'development')` instead to allow the manual CI testing of "main like" branches.

2023-09-25 13:44 UTC, bensze01 commented on vars/psa_crypto.groovy
> +        echo 'PR target is not "main" branch - not building.'
Sure, that works for me as well.

2023-09-25 13:52 UTC, ronald-cron-arm commented on vars/psa_crypto.groovy
> +        echo 'PR target is not "main" branch - not building.'
In general probably but currently the development branch in psa-crypto is quite peculiar thus to me it is acceptable for it to be handled in a special manner for CI purposes.

2023-10-04 09:35 UTC, gilles-peskine-arm commented
There's a merge conflict now.

2024-12-04 09:46 UTC, mpg commented
@bensze01 Forgot to ask yesterday, regarding the labels: does "needs CI" mean that you want to run more test jobs, or that the test jobs so far revealed issues that need fixing? (From the absence of "needs work" I'm assuming it's the former, I'm just checking to be sure.)

2024-12-04 16:34 UTC, bensze01 commented
@mpg The latter. I pushed a small drive-by fix for an issue that was hindering my testing, but aside from this no further rework should be required.

2024-12-05 09:38 UTC, mpg reviewed
Code looks good to me. I'm just waiting for all the test runs before I formally approve.

2024-12-05 17:05 UTC, minosgalanakis approved these changes
LGTM

2024-12-05 23:33 UTC, bensze01 commented
I've added all of the tests I was planning to run to the PR description.

2024-12-06 09:01 UTC, bensze01 commented
@mpg All the CI runs passed.

2024-12-06 09:07 UTC, mpg approved these changes
I had a look at the tests runs, and it all looks good to me. Thanks!

2024-12-06 09:08 UTC, merged