Create a developer guide
Mbed-TLS/mbedtls-test pull request #126
Opened 2023-09-27 18:05 UTC by gilles-peskine-arm

* Describe the general structure of the CI and the CI scripts.
* Write a few points of advice. There could be plenty more.
* Write a bit of guidance on validating CI changes.

There are no completeness goals here. I will take requests but I don't intend to spend much more time on this. Follow-ups are very welcome.

2023-11-02 10:59 UTC, tgonzalezorlandoarm submitted a review, later dismissed
This all looks good and I found it quite useful, thanks!

2023-11-06 19:14 UTC, tom-daubney-arm requested changes
Looks mostly good to me. Well written and clear and I learned a lot reading this.

Few small nits to sort out before approval. I am sorry I didn't use the suggestions feature for typos but for some reason this button does not appear on comment boxes for me in the "review view" but only when I look at the "files changed" tab, which I don't really understand but there we are.

2023-11-06 19:14 UTC, tom-daubney-arm commented on developer_guide.md
> +There are pull requests for testing various kinds of failure in the [`mbedtls-restricted` repository](https://github.com/Mbed-TLS/mbedtls-restricted/labels/ci-testing) (private link). See [“CI testin
Typo: "failure" --> "failures"

2023-11-06 19:28 UTC, tom-daubney-arm approved these changes
LGTM, thanks!

2023-11-06 19:28 UTC, gilles-peskine-arm commented
> I didn't use the suggestions feature for typos

I don't mind, it's more work to use that for typos anyway.

> but for some reason this button does not appear on comment boxes for me in the "review view" but only when I look at the "files changed" tab, which I don't really understand but there we are.

The button only appears when GitHub knows how to generate a usable patch. It appears when you look at the whole diff, but not always when you're looking at a subset of the commits. In particular it never appears if there's a commit that's not included in your view that affects the same lines, since the patch couldn't be applied to the pull request.

2023-11-06 19:29 UTC, tom-daubney-arm commented
> > I didn't use the suggestions feature for typos
> 
> I don't mind, it's more work to use that for typos anyway.
> 
> > but for some reason this button does not appear on comment boxes for me in the "review view" but only when I look at the "files changed" tab, which I don't really understand but there we are.
> 
> The button only appears when GitHub knows how to generate a usable patch. It appears when you look at the whole diff, but not always when you're looking at a subset of the commits. In particular it never appears if there's a commit that's not included in your view that affects the same lines, since the patch couldn't be applied to the pull request.

Ah cool, good to know. Thanks.

2023-11-07 10:32 UTC, tgonzalezorlandoarm submitted a review, later dismissed
LGTM, Thanks!

2024-11-18 13:05 UTC, Harry-Ramsey approved these changes
LGTM.

2025-01-06 11:43 UTC, mpg approved these changes
Looks good to me, many thanks for writing this up!

In particular the section about compatibility requirement - I hadn't realised that we need to remain compatible not just with the tip of each LTS branch, but also with the latest release in each active LTS branch, in order to support patch releases.

I have a number of suggestions for improvements, but I'm also quite in favour of merging this PR quickly, so I don't mind leaving them to follow-ups if you can't address them soon.

2025-01-06 11:43 UTC, mpg commented on developer_guide.md
> +1. Set up the Docker images (normally from a cache, but they will be rebuilt if needed).
Minor: "cache" means something else in Docker, I believe "registry" is the standard term here. I'd suggest rephrasing like "Set up the Docker images: check if the registry has images matching the current Dockerfile, otherwise rebuild and upload new images."

While at it, might add a link to https://hub.docker.com/u/trustedfirmware for Open CI (and note that Internal uses [AWS ECR](https://hub.docker.com/u/trustedfirmware).

2025-01-07 09:51 UTC, gilles-peskine-arm commented on developer_guide.md
> +* Groovy pipeline scripts under [`vars`](vars/).
TIL. (`BranchInfo` wasn't there when I wrote the guide, but `JobTimestamps` was.)

2025-01-07 10:47 UTC, gilles-peskine-arm commented on developer_guide.md
> +* Pull request (“pr-head” and “pr-merge”) jobs invoke [`mbedtls.run_job()`](vars/mbedtls.groovy). The pr-merge job only runs the “Interface stability tests” (formerly known as “ABI-API-check”). The p
The way the entry point is reached is important for most of what we do, and I'm not sure if it's the same for all jobs that reach the same entry points, so I've documented it separately.

2025-01-07 10:48 UTC, gilles-peskine-arm commented on developer_guide.md
> +1. Set up the Docker images (normally from a cache, but they will be rebuilt if needed).
It's a cache in the vernacular sense. But I've rephrased and added the Docker technical term as well as the Docker hub link.

2025-01-07 10:48 UTC, gilles-peskine-arm commented on developer_guide.md
> +The label identifies what features the executor needs to have. In particular, this encodes the operating system. We use three labels:
> (for Open CI I'd guess the config is in some gerrit repo but I don't know)

I don't know either. I'm leaving this as a TODO until someone who knows can fill it in.

2025-01-07 11:55 UTC, mpg approved these changes
LGTM, thanks for addressing my feedback!

2025-01-07 16:17 UTC, merged