Restrict automatic runs of PR jobs
Mbed-TLS/mbedtls-test pull request #129
Opened 2023-10-05 18:46 UTC by bensze01

Only run PR job if one of the following is true:
- The author of the PR is a member of a trusted Github team
- The job is triggered by the Github merge queue (thus the PR has been reviewed by a gatekeeper)
- The job was started manually from the Jenkins UI

2023-10-06 08:12 UTC, gilles-peskine-arm requested changes
I'd like a couple of clarifications, and I want to see some test runs, but the approach looks right to me.

2023-10-06 08:12 UTC, gilles-peskine-arm commented on vars/mbedtls.groovy
> +        if (!is_merge_queue && currentBuild.rawBuild.getCause(Cause.UserIdCause) == null) {
Where can I find documentation that explains `getCause(Cause.UserIdCause)`?

The [documentation of `Cause.UserIdCause`](https://javadoc.jenkins.io/hudson/model/Cause.UserIdCause.html) states

> A build is started by an user action.

It doesn't explain what a user action is, and the documentation of [`getCause`](https://javadoc.jenkins-ci.org/hudson/model/Run.html#getCause(java.lang.Class)) doesn't explain when what that function returns (and in particular when it returns `null`).

From what you've written, I guess that:

* A user action is something that happens on Jenkins. Only team members have access to jenkins, so if `getCause(Cause.UserIdCause)` returns a non-null value, it means someone with a Jenkins account explicitly triggered the build.
* The automation that triggers builds from GitHub events is not a Jenkins user.
* `getCause` returns `null` if there is no Jenkins user associated with the build trigger.

How can I validate these guesses?

2023-10-06 08:12 UTC, gilles-peskine-arm commented on vars/common.groovy
> +    return github.getOrganization('Mbed-TLS').getTeamBySlug('mbed-tls-reviewers').hasMember(author)
As discussed in chat, we should be more robust here and also allow `mbed-tls-developers` (without depending on how the lists may be nested on GitHub).

Alternatively, does the GitHub API let us test “does the user have write access on the repository?”? That would be an acceptable condition here.

2023-10-06 12:59 UTC, bensze01 commented on vars/common.groovy
> +    String credentials = is_open_ci_env ? 'mbedtls-github-token' : 'd015f9b1-4800-4a81-86b3-9dbadc18ee00'
[On the internal CI we don't have user-friendly names for our credential IDs][1], only UUIDs - we should probably ask the Infra team to rename the credentials and adopt the names the OpenCI uses at some point so we can get rid of all similar code fragments.

[1]: https://jenkins-mbedtls.oss.arm.com/credentials/

2023-10-06 14:02 UTC, bensze01 commented on vars/mbedtls.groovy
> +        if (!is_merge_queue && currentBuild.rawBuild.getCause(Cause.UserIdCause) == null) {
[`getCause` iterates over all causes of a build, and returns a cause that is an instance of `type`][1] - if no such cause is found, it returns `null`.

The following are all the causes produced by the various triggers used on our CI:
- [`Cause.UserIdCause`][2] - used for builds started through the web UI or the REST api using a user's personal access token
- [`ReplayCause`][3] - used in conjunction with `Cause.UserIdCause` for replayed builds
- [`RebuildCause`][4] - used on the OpenCI in conjuction with `Cause.UserIdCause` and *all the causes of the original build* (!) if you click the *other*, "triangular" rebuild button on their web UI, (this one picks up the most recent CI scripts, instead of "replaying" like the other button does. Unfortunately both are labelled "Rebuild" on the OpenCI.
- [`BranchIndexingCause`][5] - used for builds stared while scanning a repository, eg. the nightly scan of the repo for PR-merge jobs
-  [`BranchEventCause`][6] - used for builds started by a github webhook
- [`TimerTrigger.TimerTriggerCause`][7] - used for builds started by a plain timer
- [`ParameterizedTimerTriggerCause`][8]  - used for builds started by a parameterized timer

On the internal CI, these causes each have their own pictograms that you can hover over for a short description of the build cause [on the page listing all the runs of a single branch][9].

On both CIs, you can get a list of all causes of a build, including their full qualified classnames by appending `api/json?pretty=true` to the classic web UI's build page.

Examples for each build cause:
- [`Cause.UserIdCause`][10] 
- [`ReplayCause` + `Cause.UserIdCause`][11]
- [`RebuildCause` + `Cause.UserIdCause` +`BracnhEventCause` copied from the original build][12] 
- [`BranchIndexingCause`][13] 
-  [`BranchEventCause`][14]
- [`TimerTrigger.TimerTriggerCause`][15]
- [`ParameterizedTimerTriggerCause`][16]


[1]: https://github.com/jenkinsci/jenkins/blob/6fdfdd01c6c551777b9ff7d7abd6d86536b281b0/core/src/main/java/hudson/model/Run.java#L615-L620
[2]: https://javadoc.jenkins.io/hudson/model/Cause.UserIdCause.html
[3]: https://javadoc.jenkins.io/plugin/workflow-cps/org/jenkinsci/plugins/workflow/cps/replay/ReplayCause.html
[4]: https://javadoc.jenkins.io/plugin/rebuild/com/sonyericsson/rebuild/RebuildCause.html
[5]: https://javadoc.jenkins.io/plugin/branch-api/jenkins/branch/BranchIndexingCause.html
[6]: https://javadoc.jenkins.io/plugin/branch-api/jenkins/branch/BranchEventCause.html
[7]: https://javadoc.jenkins.io/hudson/triggers/TimerTrigger.TimerTriggerCause.html
[8]: https://javadoc.jenkins.io/plugin/parameterized-scheduler/org/jenkinsci/plugins/parameterizedscheduler/ParameterizedTimerTriggerCause.html
[9]: https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-ci-testing/view/change-requests/job/PR-7959-head/
[10]: https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-ci-testing/view/change-requests/job/PR-7959-head/4/api/json?pretty=true
[11]: https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-ci-testing/view/change-requests/job/PR-7959-head/3/api/json?pretty=true
[12]: https://mbedtls.trustedfirmware.org/job/mbed-tls-restricted-pr-ci-testing/view/change-requests/job/PR-806-head/16/api/json?pretty=true
[13]: https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-ci-testing/view/change-requests/job/PR-7959-head/2/api/json?pretty=true
[14]: https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-ci-testing/view/change-requests/job/PR-7959-head/1/api/json?pretty=true
[15]: https://jenkins-mbedtls.oss.arm.com/job/repo-scan-scheduler/1037/api/json?pretty=true
[16]: https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-nightly-tests/3691/api/json?pretty=true

2023-10-06 16:53 UTC, bensze01 commented on vars/common.groovy
> +    return github.getOrganization('Mbed-TLS').getTeamBySlug('mbed-tls-reviewers').hasMember(author)
Both are possible - I went with checking for write access, because that approach makes half as many calls to the Github REST api.

2023-10-07 08:03 UTC, gilles-peskine-arm approved these changes
Looks good to me on code reading. Though I'd like to see some test jobs before this is merged.

2023-10-09 16:50 UTC, paul-elliott-arm approved these changes
Code looks good to me, but test runs still required before full approval.

2023-10-09 17:04 UTC, bensze01 commented
@gilles-peskine-arm @paul-elliott-arm I've updated the PR descriptions with the test runs I've run so far.
Is there anything else I didn't cover that you would like to see tested before we merge this?

2023-10-09 17:17 UTC, gilles-peskine-arm commented
I started a test run with an expected failure, to make sure we haven't somehow broken the error reporting path. If that works as expected (as well as the pass-expected test runs that are still running), then I'm happy with the testing.

2023-10-09 20:50 UTC, gilles-peskine-arm commented
I've looked at the CI results and they look fine to me. Ok to merge if Paul agrees.

2023-10-10 11:18 UTC, paul-elliott-arm commented
Agreed, everything looks good. Merging.

2023-10-10 11:19 UTC, merged