speed up analyze-outcomes stage
Mbed-TLS/mbedtls-test pull request #144
Opened 2024-01-02 12:17 UTC by daverodgman

Improve perf of the analyse-outcomes stage of CI, which especially matters because it's a serial stage of the CI pipeline.

Currently, it takes around 247s to run xz on the CI.

Testing locally, current xz command takes 130s. With -0, it takes 15s (so expect ~28.5s on CI). This increases compressed size from 38 MB to 54 MB.

Using -T8 (8 threads) reduces it further to 2.6s locally (expect ~5s on CI). There's no penalty for going too big on thread count, but no benefit beyond about 8-16.

lzma, gzip, bzip2, zip are all worse.

Also, use grep instead of awk to extract failures, which saves a few more seconds.

2024-01-02 12:36 UTC, gilles-peskine-arm requested changes
OK to switch to grep, but only if the limitation is documented.

Not ok to use more threads than we have cores.

2024-01-02 12:36 UTC, gilles-peskine-arm commented on vars/analysis.groovy
> +grep ';FAIL;' outcomes.csv >"failures.csv"
This allows false positives if a test suite or a test case description is “FAIL”. I can live with that, but it requires a comment.

2024-01-02 12:36 UTC, gilles-peskine-arm commented on vars/analysis.groovy
> +grep ';FAIL;' outcomes.csv >"failures.csv"
GNU grep (at least some versions around the vintage we have on our CI) can be slow due to its handling of multibyte characters even when the pattern is pure ASCII. This only comes up in multibyte locales (e.g. `LC_CTYPE=en_US.UTF-8`). I think we have all locale categories set to `C` on the CI, but just in case, it would be more robust to explicitly set `LC_CTYPE` (or for that matter `LC_ALL`) to `C` when running `grep` and concerned about speed.

2024-01-02 12:36 UTC, gilles-peskine-arm commented on vars/analysis.groovy
> +    xz -0 -T8 failures.csv
Why `-T8`? AFAIK we don't have 8-core executors on the CI.

Beware of insisting on too much parallelism: this can create a load spike that slows down other executors, resulting in worse performance overall. You can't measure the impact just by running one job.

> Using -T8 (8 threads) reduces it further to 2.6s locally (expect ~5s on CI). There's no penalty for going too big on thread count, but no benefit beyond about 8-16.

Measuring on a machine with a different number of cores is not useful to guess at the performance on the CI.

2024-01-02 12:36 UTC, gilles-peskine-arm commented on vars/analysis.groovy
> +    xz -0 -T8 failures.csv
> lzma, gzip, bzip2, zip are all worse.

I'd expect them to result in worse compression, but maybe we're ok with less compression but less CPU consumption?

2024-01-02 12:39 UTC, daverodgman commented on vars/analysis.groovy
> +    xz -0 -T8 failures.csv
The trade-off looked non-favourable in all cases; the closest was probably gzip, which is faster (in single-thread mode, but it doesn't have a multi-thread mode), but almost twice as big output - so `xz -T<n>` wins overall.

2024-01-02 12:44 UTC, gilles-peskine-arm commented on vars/analysis.groovy
> +    xz -0 -T8 failures.csv
Multithreaded mode may be counterproductive anyway, but have you tried `pigz`? (In a realistic scenario, not on your machine!)

2024-01-02 12:48 UTC, daverodgman commented on vars/analysis.groovy
> +    xz -0 -T8 failures.csv
`pigz -1` does look considerably better for both perf (0.36s locally) and size (25 MB, about 2x better).

2024-01-02 12:54 UTC, gilles-peskine-arm commented on vars/analysis.groovy
> +    xz -0 -T8 failures.csv
By the way, we need to keep in mind that another element of the compromise is storage. That's the reason we compress, not to save on download time/bandwidth. A vast majority of outcome files are never consumed, but all are stored for some time. I don't know how much we're spending on storage, and in particular how the (compressed) outcome files compare with logs.

2024-01-02 12:58 UTC, daverodgman commented on vars/analysis.groovy
> +    xz -0 -T8 failures.csv
We can always up the storage budget if we need to. As it stands, an extra 18 MB / PR run is unlikely to cause big budget issues IMO.

2024-01-02 13:15 UTC, daverodgman commented on vars/analysis.groovy
> +    xz -0 -T8 failures.csv
I'm tracking the `pigz` suggestion as a separate follow-up, since that requires additional CI work beyond the scope of this PR.

2024-01-02 13:41 UTC, tom-cosgrove-arm submitted a review, later dismissed

2024-01-02 13:47 UTC, gilles-peskine-arm commented on vars/analysis.groovy
> +    LC_ALL=C xz -0 -T8 failures.csv
`LC_ALL=C` was supposed to apply to `grep`, not `xz`.

2024-01-02 13:53 UTC, gilles-peskine-arm commented on vars/analysis.groovy
> +    xz -0 -T8 failures.csv
I still don't see a reason to use `-T8`. Why not `-T0`?

As far as I understand, the actual number of threads is limited by the memory consumption (which I don't expect to matter at `-O0`), by the `-T` value and by the file size, but not by the number of cores. Looking at the `xz` source code, `lzma_cputhreads()` is called to determine what `hardware_threads_get()` will return when using `-T0`, and then the encoder only relies on `hardware_threads_get()` and not `lzma_cputhreads()`.

Since 8 is an arbitrary number here, I'd want to see some benchmark that justifies it. Otherwise please use `-T0` (the number of cores seems like a sensible default choice).

2024-01-03 08:13 UTC, tom-cosgrove-arm approved these changes
LGTM

2024-01-03 08:14 UTC, tom-cosgrove-arm commented
CI is green

@gilles-peskine-arm are you happy enough with this now to approve?

2024-01-03 09:22 UTC, gilles-peskine-arm commented on vars/analysis.groovy
> +    xz -0 -T8 failures.csv
This is still unaddressed.

2024-01-03 11:04 UTC, daverodgman commented
@gilles-peskine-arm I have updated to use `-T0`, please review

2024-01-03 11:21 UTC, tom-cosgrove-arm approved these changes

2024-01-03 19:39 UTC, gilles-peskine-arm approved these changes
Looks good to me on code inspection.

Ok to merge with a passing CI run (either release or PR will do).

2024-01-04 14:47 UTC, daverodgman commented
Test run shows xz taking 15s https://jenkins-mbedtls.oss.arm.com/blue/rest/organizations/jenkins/pipelines/mbed-tls-pr-head/branches/PR-8530-head/runs/12/nodes/8129/log/?start=0

2024-01-04 14:47 UTC, merged