Run result analysis in Docker
Mbed-TLS/mbedtls-test pull request #166
Opened 2024-04-26 09:14 UTC by gilles-peskine-arm

[Run result analysis in the same environment as test jobs: in a Docker image, with our Python requirements installed. This does most of the work towards https://github.com/Mbed-TLS/mbedtls/issues/8300: we'll be able to run `make generated_files`.

We could finish resolving  https://github.com/Mbed-TLS/mbedtls/issues/8300 here by running `tests/scripts/check-generated-files.sh -u` here. (Not `make generated_files` because that doesn't exist in 2.28.) But I would prefer to pull the switch in an `mbedtls` pull request that changes `analyze_outcomes.py` to run `make generated_files`. I'm open to counter-arguments though.

Also, as a result of refactoring:

* Resolves https://github.com/Mbed-TLS/mbedtls-test/issues/134
* Resolves https://github.com/Mbed-TLS/mbedtls-test/issues/120

Test jobs on d39c220cc5c950f17268540650816e2aa5638c8d:

* Release job on `development`: [OpenCI](https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/189/) (log of [result analysis](https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/189/execution/node/8997/log/))
* Release job in `mbedtls-2.28`: [OpenCI](https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/190/) (log of [result analysis](https://mbedtls.trustedfirmware.org/job/mbedtls-release-ci-testing/190/execution/node/7238/log/))
* PR job with [outcome analysis failure](https://github.com/Mbed-TLS/mbedtls-restricted/pull/1225): TODO
* PR job with [build failures](https://github.com/Mbed-TLS/mbedtls-restricted/pull/759): [OpenCI](https://mbedtls.trustedfirmware.org/job/mbed-tls-restricted-pr-ci-testing/job/PR-759-head/9/)
* PR-merge job with [passing ABI check](https://github.com/Mbed-TLS/mbedtls-restricted/pull/906): [OpenCI](https://mbedtls.trustedfirmware.org/job/mbed-tls-restricted-pr-ci-testing/view/change-requests/job/PR-906-merge/15/)
* PR-merge job with [failing ABI check](https://github.com/Mbed-TLS/mbedtls-restricted/pull/758): [OpenCI](https://mbedtls.trustedfirmware.org/job/mbed-tls-restricted-pr-ci-testing/view/change-requests/job/PR-758-merge/4/)

2024-05-09 17:24 UTC, paul-elliott-arm submitted a review, later dismissed
LGTM

2024-05-17 12:22 UTC, bensze01 requested changes
I found two nits in this PR, otherwise looks to be in good shape to me.

2024-05-17 12:22 UTC, bensze01 commented on vars/gen_jobs.groovy
> + */
I'd suggest turning this into a Javadoc comment so it's picked up by IDEs.
I've added some Javadoc markup to this effect - hopefully it doesn't reduce the plain-text readability too much.
```suggestion
// gen_docker_job(info, job_name, platform, script_in_docker, ...)
/**
 * Construct a job that runs a script in Docker.
 *
 * @return
 *     A one-element map mapping job_name to a closure that runs the job.
 *
 * @param info
 *     A BranchInfo object describing the branch to test.
 * @param job_name
 *     The name to use for the job. It is used as a key in
 *     the returned map, as a name in Jenkins reports and logs, to
 *     construct file names and anywhere else this function needs
 *     a presumed unique job name.
 * @param platform
 *     The name of the Docker image.
 * @param script_in_docker
 *     A shell script to run in the Docker image.
 *
 * @param hooks
 *     Named parameters
 *     <dl>
 *         <dt>{@code post_checkout}</dt><dd>
 *             Hook that runs after checking out the code to test.
 *         </dd>
 *         <dt>{@code post_success}</dt><dd>
 *             Hook that runs after running the script in Docker, if
 *             that script succeeds.
 *         </dd>
 *         <dt>{@code post_execution}</dt><dd>
 *             Hook that runs after running the script in Docker,
 *             whether it succeeded or not. It can check the job's status by querying
 *             {@code gen_jobs.failed_builds[job_name]}, which is true if the job failed and
 *             absent otherwise. This hook should not throw an exception.
 *         </dd>
 *     </dl>
 *
 *     All hook parameters are closures that are called with no arguments.
 *     They can be null, in which case the hook does nothing. The code runs
 *     on a 'container-host' executor, in the directory containing the
 *     source code.
 */
```

2024-05-17 12:53 UTC, gilles-peskine-arm commented on vars/mbedtls.groovy
>          try {
Yes, and also we shouldn't send the email for nightlies before the result analysis has run.

I don't understand the part about making a separate stage, however.

2024-05-17 13:30 UTC, bensze01 approved these changes
Looks good to me on code inspection, waiting for the CI results.

2024-05-21 16:52 UTC, paul-elliott-arm approved these changes
LGTM

2024-05-21 18:05 UTC, merged