Run API-ABI check on Ubuntu 18.04
Mbed-TLS/mbedtls-test pull request #168
Opened 2024-06-18 08:49 UTC by bensze01

The version of Git on 16.04 does not attempt to fetch submodule commits by hash, causing CI failures if PRs are submitted to the framework repo from forks.

2024-06-18 08:56 UTC, gilles-peskine-arm requested changes
IIRC https://github.com/Mbed-TLS/mbedtls/issues/5332 affects 18.04 as well. Or did you check that it doesn't?

2024-06-19 13:57 UTC, bensze01 commented
The ABI break test produced correct results, as far as I can tell: [Internal](https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-pr-ci-testing/view/change-requests/job/PR-758-merge/1/) / [Open CI](https://mbedtls.trustedfirmware.org/job/mbed-tls-restricted-pr-ci-testing/view/change-requests/job/PR-758-merge/7/)

2024-06-19 14:44 UTC, gilles-peskine-arm approved these changes
LGTM

2024-06-20 06:35 UTC, ronald-cron-arm approved these changes
LGTM

2024-06-20 08:06 UTC, merged