Fix call to send_email() in run_release_job()
Mbed-TLS/mbedtls-test pull request #182
Opened 2024-11-06 13:37 UTC by bensze01

This call was missed / accidentally dropped during a rebase of commit 8d9b2b78df05a3bd0ef90e4cfe021373fc65c652.

Also initialize infos at declaration, so an early failure doesn't result in a null pointer dereference in the finally block.

2024-11-06 14:30 UTC, gilles-peskine-arm submitted a review, later dismissed
Looks good to me on code reading.

2024-11-06 15:14 UTC, paul-elliott-arm submitted a review, later dismissed
LGTM (Certainly makes sense anyway)

2024-11-06 15:25 UTC, bensze01 commented
Pushed a commit enabling testing the email mechanism, plus a small logic fix and a drive-by improvement of `send_email()` I made while working on the former.

2024-11-06 17:02 UTC, paul-elliott-arm reviewed
LGTM at least by inspection (provided successful test runs)

2024-11-06 17:06 UTC, gilles-peskine-arm requested changes
We've lost a bit of useful logging, and I'm not sure if the job configurations need changing.

2024-11-06 17:06 UTC, gilles-peskine-arm commented on vars/common.groovy
>          recipients = env.TEST_PASS_EMAIL_ADDRESS
So now the job configuration and/or runtime parameters determine whether to send an email. I like that. (In addition to being more robust, it means we can fire a job and get an email notification when it's finished, if we care.) Do we need to revise the configuration of some jobs to start offering the `TEST_xxx_EMAIL_ADDRESSES` environment variable in parametrized builds, or to make them empty by default? For example [`mbedtls-restricted-release-new` on OpenCI lists `TEST_FAIL_EMAIL_ADDRESS`](https://review.trustedfirmware.org/plugins/gitiles/ci/mbedtls/mbed-tls-job-configs/+/refs/heads/master/mbedtls-restricted-release-new.yaml), but AFAICT it's a hard-coded list, not a property we can change.

2024-11-06 17:10 UTC, bensze01 commented on vars/common.groovy
>          recipients = env.TEST_PASS_EMAIL_ADDRESS
It is already a parameter on the internal CI. Will push a gerrit change that parametrizes it on the OpenCI as well.

2024-11-06 18:09 UTC, gilles-peskine-arm submitted a review, later dismissed
Looks good to me on code inspection, assuming we update the relevant job configurations to make `TEST_{PASS,FAIL}_EMAIL_ADDRESSES` environment variables with suitable defaults.

2024-11-06 19:04 UTC, gilles-peskine-arm approved these changes
LGTM (pending test jobs being ok, and assuming the necessary configuration changes are done)

2024-11-06 20:07 UTC, bensze01 commented on vars/common.groovy
>          recipients = env.TEST_PASS_EMAIL_ADDRESS
Job config change to parametrize this on the OpenCI:
https://review.trustedfirmware.org/c/ci/mbedtls/mbed-tls-job-configs/+/33347

Not sure whether all of the default e-mail addresses are correct/active, so I've left them in place for now where they were effectively being used prior to this PR.

2024-11-07 09:50 UTC, bensze01 commented
All CI runs passed, config change merged.

2024-11-07 14:02 UTC, merged