Run TF-PSA-Crypto components without cloning Mbed TLS
Mbed-TLS/mbedtls-test pull request #190
Opened 2024-12-20 16:51 UTC by bensze01

Test runs: TBD

2025-01-07 11:34 UTC, mpg reviewed
Just making myself familiar with the code.

Note: we'll want a test run showing that if a tf-psa-crypto component tries to reference an Mbed TLS file, it fails. (We'll probably want to create a faulty PR for that purpose.)

2025-01-07 11:34 UTC, mpg commented on vars/common.groovy
> +                                echo "All all.sh components: ${all.join(" ")}"
Minor should probably adjust the message as well: All all.sh -> <repo> all.sh?

2025-01-07 11:34 UTC, mpg commented on vars/gen_jobs.groovy
> +    if (repo == 'tls' && info.has_min_requirements) {
I'm not sure I understand why we need the `repo == 'tls'` part: currently `tf-psa-crypto` doesn't have `scripts/min_requirements.py` but I'd guess `info.has_min_requirements` should reflect that?

2025-01-07 11:34 UTC, mpg commented on vars/gen_jobs.groovy
>                  checkout_repo.checkout_tls_repo(info)
Don't you mean to remove this line?

2025-01-07 11:34 UTC, mpg commented on vars/gen_jobs.groovy
> +            jobs = jobs + gen_all_sh_jobs(info, platform, component, label_prefix)
Shouldn't we pass `'tf-psa-crypto'` as the last argument? Otherwise it will default to `'tls'`.

2025-01-07 12:03 UTC, mpg commented on vars/gen_jobs.groovy
> +    if (repo == 'tls' && info.has_min_requirements) {
Also, it seems to me we'll need to get `scripts/min_requirements.py` (and supporting files) in tf-psa-crypto (or the framework) before moving python scripts that have requirements beyond what happens to be already installed by apt. @ronald-cron-arm not sure if that dependency was already on your radar?

2025-01-07 17:47 UTC, ronald-cron-arm commented on vars/gen_jobs.groovy
> +    if (repo == 'tls' && info.has_min_requirements) {
No that was not on my radar. I can see that @valeriosetti has started working on https://github.com/Mbed-TLS/mbedtls-framework/issues/86. Does this issue fully cover the dependency?

2025-01-09 04:40 UTC, valeriosetti commented on vars/gen_jobs.groovy
> +    if (repo == 'tls' && info.has_min_requirements) {
> I can see that @valeriosetti has started working on https://github.com/Mbed-TLS/mbedtls-framework/issues/86.

Yes, PRs https://github.com/Mbed-TLS/mbedtls-framework/pull/105 and related ones (https://github.com/Mbed-TLS/mbedtls/pull/9863 https://github.com/Mbed-TLS/mbedtls/pull/9864) are ready for review. There's only the usual `framework` confict on `development` and `mbedtls-3.6`, but that can easily be fixed once https://github.com/Mbed-TLS/mbedtls-framework/pull/105 is merged.

2025-01-13 02:09 UTC, bensze01 commented on vars/gen_jobs.groovy
> +    if (repo == 'tls' && info.has_min_requirements) {
@mpg Currently the code only checks if `min_requirements.py` exists in the MbedTLS branch we are testing, and this is what's represented by `has_min_requirements`. Since we're planning to add such a script, I'll add a separate variable to track this for the framework.

2025-01-13 04:31 UTC, valeriosetti commented on vars/gen_jobs.groovy
> +    if (repo == 'tls' && info.has_min_requirements) {
For the records, I created https://github.com/Mbed-TLS/TF-PSA-Crypto/pull/148 to add `min_requirements.py` to TF-PSA-Crypto

2025-01-13 08:31 UTC, mpg commented on vars/gen_jobs.groovy
> +    if (repo == 'tls' && info.has_min_requirements) {
> Since we're planning to add such a script, I'll add a separate variable to track this for the framework.

Not sure if this was a typo, but just to be sure: I was talking about tf-psa-crypto, not the framework. Currently the plan is for `scripts/min_requirements.py` to exist only in the two "top-level" repos (mbedtls, tf-psa-crypto).

2025-01-13 11:21 UTC, bensze01 commented on vars/gen_jobs.groovy
> +    if (repo == 'tls' && info.has_min_requirements) {
Ah, yes sorry, that was a typo - I meant tf-psa-crypto.

2025-02-12 04:54 UTC, bensze01 commented
@mpg I think I've addressed all the feedback. 
Adding support for `min_requirements.py` required a major refactor that brought the design back closer to the way `get_branch_information()` was set up, so I've squashed the back-and-forth changes to hopefully make reviewing this PR easier.

2025-02-13 07:49 UTC, bensze01 commented
All the test runs completed successfully.

2025-02-18 14:48 UTC, ronald-cron-arm requested changes

2025-02-18 14:48 UTC, ronald-cron-arm commented on vars/common.groovy
> +List<BranchInfo> get_branch_information(Collection<String> tls_branches) {
As discussed offline it seems it would be better to have another argument here with the tf-psa-crypto branches that would bubble up into `run_pr_job()` signature as well rather than adding here a `tf-psa-crypto` branch based on `env.RUN_TF_PSA_CRYPTO_ALL_SH`. This should help as well when we add the TF-PSA-Crypto development branch as a branch to be tested as part of the framework CI.

2025-02-21 09:34 UTC, ronald-cron-arm commented
@bensze01 have you run new tests with the last version?

2025-02-24 09:44 UTC, yanesca reviewed
I left a couple of remarks inline.

Also, commit "Test tf-psa-crypto components without Mbed TLS" a lot of things are happening:
1. Adds a function for unified handling of repo checkout
2. Adds another level of loop for dealing with multiple repos when collecting branch information
3. Restricts non-all.sh jobs to the tls repo (with the exception of analyse outcomes which follows in the next commit)
4. Extends prefix handling to handle multiple repos
I am not asking for any changes here, just for future reference, in similar
cases breaking something like this down into more commits helps review and future development.

Overall I didn't find any blockers, the only reason I am not approving yet because I have a question about the test runs:
The reason for failure seems unrelated to this PR, still it makes me wonder if we understand what is going on there and why we don't want to get a green CI?

2025-02-24 10:21 UTC, yanesca approved these changes
> the only reason I am not approving yet because I have a question about the test runs

Oh, never mind, it is the ongoing CI incident.

2025-02-24 10:26 UTC, bensze01 commented on vars/mbedtls.groovy
> +        [tls_branches, tf_psa_crypto_branches].collect({branches -> branches.split(',').findAll()})
I'm using `findAll()` instead of `as List` to filter out any empty strings returned by `.split(',')`.
Eg.:
```
''.split(',') as List == [ '' ]
''.split(',').findAll() == []
```

2025-02-24 10:29 UTC, bensze01 commented on vars/mbedtls.groovy
> +void run_pr_job(String target_repo, boolean is_production, Collection<String> tls_branches, Collection<String> tf_psa_crypto_branches) {
`Object[].findAll()` returns a `Collection` in its method signature (really an `ArrayList`, but that's an implementation detail)

2025-02-25 07:53 UTC, bensze01 commented
@mpg @yanesca I've rebased the PR on top of `main`, and all the CI runs passed.

2025-02-25 08:31 UTC, yanesca submitted a review, later dismissed
Did the rebase and arrived at the same result.

2025-03-03 14:16 UTC, ronald-cron-arm requested changes
This looks almost good to me. I have a few comments though.

2025-03-03 15:27 UTC, bensze01 commented on vars/mbedtls.groovy
> +    run_pr_job('framework', true, ['development', 'mbedtls-3.6'], ['development'])
It is possible to test this through `mbed-tls-restricted-pr-test-parametrized`, [by specifying multiple branches separated by commas](https://github.com/Mbed-TLS/mbedtls-test/blob/1cfc68d72a9874e3c82762404710fd7cbc67e264/vars/mbedtls.groovy#L65-L69).

2025-03-03 15:32 UTC, ronald-cron-arm commented on vars/mbedtls.groovy
> +    run_pr_job('framework', true, ['development', 'mbedtls-3.6'], ['development'])
Ah great, could you test it then?

2025-03-06 08:56 UTC, bensze01 commented
All the tests (including the framework CI ones) have passed, please re-review, @yanesca @ronald-cron-arm.

2025-03-10 09:44 UTC, ronald-cron-arm approved these changes
This looks good to me, thanks.

2025-03-10 14:38 UTC, yanesca approved these changes
LGTM

2025-03-10 14:39 UTC, merged