Improve dockerfile Readme
Mbed-TLS/mbedtls-test pull request #83
Opened 2022-12-15 09:08 UTC by mpg

Mainly trying to make it more discoverable how to fetch images used by the CI.

2022-12-15 11:24 UTC, yuhaoth commented
I have push all package in https://hub.docker.com/repository/docker/yuhaoth/sources . To use that put below line in dockerfile.

```dockerfile
copy --from=yuhaoth/sources pre-builts/DS500-PA-00003-r5p0-22rel0.tgz /opt
```

2022-12-15 11:36 UTC, mpg commented
@yuhaoth isn't that more related to this other issue? https://github.com/Mbed-TLS/mbedtls-test/issues/77

2022-12-15 11:44 UTC, yuhaoth commented
> @yuhaoth isn't that more related to this other issue? #77

move to #77

2022-12-16 14:17 UTC, davidhorstmann-arm commented on resources/docker_files/README.md
> +## Re-builing images locally
Typo: "Re-builing" -> "Re-building"

2022-12-16 15:01 UTC, davidhorstmann-arm requested changes
A few typos and nits but looks good otherwise!

2022-12-16 15:01 UTC, davidhorstmann-arm commented on resources/docker_files/README.md
>  Note: `--network=host` may or may not necessary depending on your machine's
```suggestion
Note: `--network=host` may or may not be necessary depending on your machine's
```

2022-12-16 15:01 UTC, davidhorstmann-arm commented on resources/docker_files/README.md
> +## Re-builing images locally
```suggestion
## Re-building images locally
```

2022-12-19 09:54 UTC, mpg commented on resources/docker_files/README.md
> +Above, ```-i``` is for interactive mode and ```-t``` is for emulating a tty. ```--rm``` tells docker to cleanup the container after exit. (See note above regarding `--network=host`.) All images launc
I disagree: the capital that starts the sentence is inside the parentheses, so the period that ends it should be inside as well. If we remove the parentheses and what's inside, the result should still be valid, not have two periods in a row.

2022-12-19 10:00 UTC, mpg commented
@davidhorstmann-arm Thanks for your review! I applied your suggestions, except one.

2022-12-19 14:21 UTC, gilles-peskine-arm commented on resources/docker_files/README.md
> +Above, ```-i``` is for interactive mode and ```-t``` is for emulating a tty. ```--rm``` tells docker to cleanup the container after exit. (See note above regarding `--network=host`.) All images launc
Which one is correct English typography depends on which style manual you read. IIRC the US and the UK tend to have different preferences but there are minority opinions on both sides. So let's not get hung up on this and accept whatever's written.

2022-12-19 15:39 UTC, tom-cosgrove-arm commented on resources/docker_files/README.md
> +Above, ```-i``` is for interactive mode and ```-t``` is for emulating a tty. ```--rm``` tells docker to cleanup the container after exit. (See note above regarding `--network=host`.) All images launc
I don't think there's much disagreement that if a whole sentence is within parentheses then the punctuation at the end should also be within the parentheses. Manuel's rule-of-thumb is a good guide.

2022-12-20 09:20 UTC, mpg commented on resources/docker_files/README.md
> +Above, ```-i``` is for interactive mode and ```-t``` is for emulating a tty. ```--rm``` tells docker to cleanup the container after exit. (See note above regarding `--network=host`.) All images launc
> So let's not get hung up on this and accept whatever's written.

I think that's a good general principle: if there's disagreement among natives speakers (of the same or opposite sides of the pond), then let's accept whatever's already there.

> I don't think there's much disagreement

Well, David just suggested a change here... let's not get into meta-disagreements about the existence of a disagreement ;)

2023-01-03 13:05 UTC, davidhorstmann-arm commented
LGTM - thanks!

2023-01-03 13:35 UTC, tom-cosgrove-arm commented on resources/docker_files/README.md
> +This creates an image from the specified file. The built image is maintained by docker in it's own workspace on the host. Don't worry where the built image is gone! From this point the built image is
Grr, just noticed (sorry) (and pre-existing, but horrible): `it's` is an abbreviation for `it is`; the possessive should be `its` (twice in this paragraph).

Also, in lots of places, triple backticks are used inline - I alway thought that triple backticks give code blocks, and single ones should be used inline.

2023-01-06 10:13 UTC, tom-cosgrove-arm commented on resources/docker_files/README.md
> +Docker files for some of the supported platforms are provided here. These are prepared with all necessary tools for building and testing Mbed TLS library and its sample applications (as tested in the
`s/enviroment/environment`

2023-01-06 10:18 UTC, tom-cosgrove-arm commented on resources/docker_files/README.md
> +sudo docker images
Docker-related question: isn't `sudo` only needed if your regular user isn't in the correct group? (i.e. generally you want to not need to type `sudo` in front of everything, as that then becomes muscle memory, with appropriately unfortunate consequences at time ...)

2023-01-06 10:28 UTC, mpg commented on resources/docker_files/README.md
> +sudo docker images
Last time I checked, adding your user to the appropriate group was [effectively equivalent* to giving it passwordless sudo](https://fosterelli.co/privilege-escalation-via-docker.html). So, some people prefer not to add their user to that group, and instead type sudo when needed.

*In an adversarial model, like if you assume someone has compromised your account and for some reason that's not enough for them and they also want root on your machine (for example, to secure long-term access in a more stealthy way than they could as a normal user). It might not be equivalent in a model where the main goal is to protect against accidental mistakes.

2023-01-06 10:32 UTC, tom-cosgrove-arm commented on resources/docker_files/README.md
> +sudo docker images
Okay, thanks for the info - I wasn't aware of that. And yes, in general I assume if someone is able to compromise my account they're also able to escalate that to root, and there have been several times where needing `sudo` on a command has kept me from shooting myself in the foot - long enough, for example, to realise that I am `ssh`d into the wrong box, or not `ssh`d at all, before issuing `shutdown`!

2023-01-06 10:33 UTC, gilles-peskine-arm commented on resources/docker_files/README.md
> +Above, `-i` is for interactive mode and `-t` is for emulating a tty. `--rm` tells docker to cleanup the container after exit. (See note above regarding `--network=host`.) All images launch `bash` on
zsh user here, I say “in” but I don't care if others say “on”

2023-01-06 10:36 UTC, mpg commented
@tom-cosgrove-arm Thanks for your comments! However, I've renamed this PR to more accurately reflect its original goal, as I'd like to keep it focused on that goal, and leave other improvements for possible follow-ups, in order to improve its chances of being merged in a timely fashion :)

2023-01-06 10:57 UTC, tom-cosgrove-arm commented
Won't you at least fix the typo, even though it was pre-existing?

2023-01-06 11:28 UTC, mpg commented
> Won't you at least fix the typo, even though it was pre-existing?

Done. (Then force-pushed because I managed to make a typo in the 3-words commit message...)

2023-01-06 12:20 UTC, tom-cosgrove-arm approved these changes
LGTM

2023-01-10 08:05 UTC, merged