Add Dockerfile to build docker image for ubuntu-22.04
Mbed-TLS/mbedtls-test pull request #88
Opened 2023-01-11 11:21 UTC by yanrayw

## Description

Fix: #58 

## Comments

This PR adds Dockerfile to build docker image for ubuntu-22.04. Since we cannot download ARM Compilers temporarily, the code to download them has been commented in a separate commit.

2023-03-02 10:23 UTC, yanrayw commented
As `armcc` doesn't block docker image build, this PR is rebased and ready for review.

2023-03-02 10:25 UTC, tom-cosgrove-arm commented on resources/docker_files/ubuntu-22.04/Dockerfile
> +#  Copyright (c) 2018-2023, ARM Limited, All Rights Reserved
I didn't think we put copyright year in Mbed TLS file headers

2023-03-02 10:28 UTC, gilles-peskine-arm commented on resources/docker_files/ubuntu-22.04/Dockerfile
> +#  Copyright (c) 2018-2023, ARM Limited, All Rights Reserved
We used to. We stopped doing it in the mbedtls repository, but not here, probably because we forgot. That's out of scope here. It's fine to use the same style of comments as the other existing files.

2023-03-02 10:31 UTC, gilles-peskine-arm commented
Please run a job on both CIs (OpenCI and Internal CI) to verify that they build the new image correctly. You need to push the branch to `dev/yanrayw/58-docker-ubuntu20.04` on the main repository, then run an `mbedtls-release-ci-testing` job and select that branch. No need to tick any checkbox since nothing will be using the image yet.

2023-03-03 02:16 UTC, yanrayw commented
> Please run a job on both CIs (OpenCI and Internal CI) to verify that they build the new image correctly.

I only triggered a `mbedtls-release-ci-testing` job in [Internal CI](https://jenkins-mbedtls.oss.arm.com/job/mbedtls-release-ci-testing/440/). But I didn't see a button to `Build Parameters` in OpenCI. It looks I don't have the permission to trigger a job in OpenCI.

2023-03-03 15:11 UTC, gilles-peskine-arm requested changes

2023-03-03 15:11 UTC, gilles-peskine-arm commented on resources/docker_files/ubuntu-22.04/Dockerfile
> +        abi-compliance-checker \
Does the abi-check job work on 22.04? If not we should have the same warning as in the 20.04 image.

2023-03-06 10:54 UTC, yanrayw commented
I found I made a mistake when I created this branch `58-docker-ubuntu20.04`. It's supposed to be `58-docker-ubuntu22.04`. But this PR is under review, I think we can still use this branch because renamed branch will create another PR. Let me know if this really matters.

2023-03-06 10:58 UTC, tom-cosgrove-arm commented
Don't worry about the branch name - just leave it as it is

2023-03-06 11:08 UTC, yanrayw commented on resources/docker_files/ubuntu-22.04/Dockerfile
> +# ubuntu-22.04/Dockerfile
> I think dockerfile_builder.groovy is obsolete — @bensze01 ?

From my perspective, we can still add `ubuntu-22.04` in `dockerfile_builder.groovy` even if this file is obsolete. It might be confusing that we have `ubuntu-16.04`, `ubuntu-18.04` and `ubuntu-20.04` but no `ubuntu-22.04`. If we don't need `dockerfile_builder.groovy` anymore, maybe we could remove it in another PR. So I also changed `dockerfile_builder.groovy` in d93b255

2023-03-07 10:01 UTC, gilles-peskine-arm approved these changes
LGTM

2023-03-09 13:53 UTC, bensze01 commented on resources/docker_files/ubuntu-22.04/Dockerfile
> +# ubuntu-22.04/Dockerfile
`dockerfile_builder.groovy` was intended to support re-building unchanged Dockerfiles eg. if base image updates need to be picked up.

This use case is the only one it supports currently - if the base image has been updated, all of the Dockerfile steps will be re-run - otherwise all of the build steps will be picked up from the cache, producing an identical image.

2023-03-09 14:42 UTC, gilles-peskine-arm commented on resources/docker_files/ubuntu-22.04/Dockerfile
> +# ubuntu-22.04/Dockerfile
> dockerfile_builder.groovy was intended to support re-building unchanged Dockerfiles eg. if base image updates need to be picked up.

Ah, good point.

So it's a good thing that I forgot about it for `arm-compilers`, since we currently can't rebuild that one!

2023-03-16 02:08 UTC, lpy4105 approved these changes
LGTM

2023-03-16 08:55 UTC, merged