Separate dockerfile for Arm compilers
Mbed-TLS/mbedtls-test pull request #96
Opened 2023-02-23 18:24 UTC by gilles-peskine-arm

There are no longer any public URLs to download Arm compilers, so the Docker images can't be built from the dockerfiles anymore. Separate one Docker image with the Arm compilers, and other Docker images with only publicly available tools that anyone can build. Fix #94.

Note that we're relying on cached images for the `arm-compilers` image. Making an image that can be built from scratch if you have access to the required programs is out of scope of this pull request.

Status: I'm not sure I'm managing the transition to the new image correctly. This should work if the CI can build the new image using its cached steps, but I'm not sure if I'm giving it enough information to do so.

2023-02-23 20:53 UTC, bensze01 requested changes

2023-02-23 20:53 UTC, bensze01 commented on vars/gen_jobs.groovy
> +                            extra_build_args += " --cache-from $common.docker_repoubuntu-20.04-f15359b0ac46e767133991b76ccf23e3cd2e5e0f: "
```suggestion
                            extra_build_args += " --cache-from $common.docker_repo:ubuntu-20.04-f15359b0ac46e767133991b76ccf23e3cd2e5e0f"

```
Typo.

2023-02-24 08:27 UTC, lpy4105 reviewed
The change here looks fine to me. But since `all_u16-build_armcc` failed on both `development` and `mbedtls-2.28` branch, I created https://github.com/Mbed-TLS/mbedtls/pull/7163 to resolve the failure, and it should be merged before this PR.

2023-02-24 09:56 UTC, gilles-peskine-arm commented
Thanks for analyzing the failure @lpy4105. Unfortunately, if we merge this as is, the armcc job will fail on all PR that don't have #7163 merged. So I'll make a workaround in the groovy code.

2023-02-27 07:09 UTC, lpy4105 commented
It seems that the script didn't generate the job for `build_armcc` correctly as it still failed. I'm not very sure, but at least `node_label_for_platform` and `platform_has_docker` doesn't work correctly with the platform name `arm-compilers`

2023-02-28 16:50 UTC, gilles-peskine-arm commented
As I write, the CI is still running, but the `build_armcc` job pas passed so I think this is ready for review.

2023-02-28 23:59 UTC, bensze01 approved these changes
Looks good to me.

2023-03-01 02:19 UTC, lpy4105 approved these changes
LGTM

2023-03-01 09:27 UTC, merged